-- ERP Escoteiro — schema inicial (migrado do Firebird BANCO_SCOUTH)
-- Rode no SQL Editor do Supabase ou via CLI: supabase db push

create extension if not exists "pgcrypto";

-- Perfis ligados ao Auth do Supabase
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  empresa_id integer not null,
  nome text not null,
  username text,
  tipo char(1) default 'R',
  codigo_ramo integer,
  codigo_secao integer,
  codigo_secao_nome integer,
  created_at timestamptz not null default now()
);

create table public.empresa (
  id integer generated by default as identity primary key,
  cnpj varchar(14),
  cpf varchar(14),
  nome varchar(100) not null,
  endereco varchar(80),
  numero varchar(20),
  cep varchar(8),
  complemento varchar(80),
  cidade integer,
  estado varchar(2),
  email varchar(80),
  ativo boolean default true
);

create table public.ramos (
  ramo_id integer generated by default as identity primary key,
  nome varchar(50) not null,
  idade_inicio integer,
  idade_fim integer
);

create table public.estado (
  id integer generated by default as identity primary key,
  codigo varchar(2) not null unique,
  nome varchar(60) not null,
  ibg integer
);

create table public.cidade (
  id integer generated by default as identity primary key,
  codigo integer,
  nome varchar(100) not null,
  uf varchar(2) not null
);

create index cidade_uf_nome_idx on public.cidade (uf, nome);

create table public.categoria (
  categoria_id integer generated by default as identity primary key,
  nome varchar(50) not null
);

create table public.funcao (
  funcao_id integer generated by default as identity primary key,
  nome varchar(30) not null
);

create table public.secao (
  secao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(80) not null,
  ramo integer references public.ramos (ramo_id),
  secao_foto text
);

create table public.secao_nome (
  secaonome_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(80) not null,
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  secaonome_foto text
);

create table public.tipo_mensalidade (
  tipomensalidade_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(50) not null,
  valor numeric(15, 2) default 0
);

create table public.tipo_pagamento (
  tipopagto_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(50) not null,
  quita boolean default false
);

create table public.associados (
  associado_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  registro integer,
  registro_identificador integer,
  nome varchar(100) not null,
  endereco_cep varchar(8),
  endereco varchar(80),
  endereco_numero varchar(15),
  endereco_complemento varchar(20),
  endereco_bairro varchar(30),
  endereco_cidade integer,
  endereco_uf varchar(2),
  categoria integer references public.categoria (categoria_id),
  categoria2 integer references public.categoria (categoria_id),
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  funcao integer references public.funcao (funcao_id),
  patrulha_matilha integer references public.secao_nome (secaonome_id),
  fone_residencial varchar(20),
  celular varchar(20),
  email varchar(130),
  rg varchar(15),
  cpf varchar(15),
  data_nascimento date,
  responsavel_nome varchar(100),
  responsavel_foneresi varchar(20),
  responsavel_fonecelular varchar(20),
  responsavel_email varchar(130),
  responsavel_cpf varchar(15),
  ativo boolean default true,
  isento boolean default false,
  tipo_mensalidade integer references public.tipo_mensalidade (tipomensalidade_id),
  validade_registro date
);

create index associados_empresa_nome_idx on public.associados (empresa_id, nome);
create index associados_empresa_registro_idx on public.associados (empresa_id, registro);
create index associados_empresa_ramo_idx on public.associados (empresa_id, ramo);

create table public.grupo_produto (
  grupoproduto_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(50) not null
);

create table public.produto (
  produto_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  nome varchar(100) not null,
  grupo integer references public.grupo_produto (grupoproduto_id),
  ramo integer,
  secao integer,
  secao_nome integer,
  venda boolean default true,
  valor_venda numeric(15, 2) default 0,
  valor_custo numeric(15, 2) default 0,
  ativo boolean default true
);

create table public.produto_custo (
  produtopreco_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  produto integer references public.produto (produto_id),
  data date,
  valor numeric(15, 2)
);

create table public.produto_preco (
  produtopreco_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  produto integer references public.produto (produto_id),
  data date,
  valor numeric(15, 2)
);

create table public.fornecedor_despesa (
  fordespesa_id integer generated by default as identity primary key,
  empresa_id integer references public.empresa (id),
  fordespesa_nome varchar(70),
  fordespesa_cnpj varchar(14),
  fordespesa_tipo char(1),
  fordespesa_email varchar(60),
  fordespesa_email2 varchar(60),
  fordespesa_fone1 varchar(14),
  fordespesa_fone2 varchar(14),
  fordespesa_fone3 varchar(14),
  fordespesa_endereco varchar(60),
  fordespesa_numero varchar(10),
  fordespesa_complemento varchar(20),
  fordespesa_bairro varchar(30),
  fordespesa_uf varchar(2),
  fordespesa_cidade integer,
  fordespesa_cep varchar(8),
  fordespesa_despesa char(1)
);

create table public.despesas (
  despesa_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  despesa_ramo integer,
  despesa_secao integer,
  despesa_secaonome integer,
  despesa_titulo integer,
  despesa_fornecedor integer references public.fornecedor_despesa (fordespesa_id),
  despesa_numeronota varchar(20),
  despesa_emissao date,
  despesa_vencimento date,
  despesa_situacao integer,
  despesa_valor numeric(15, 2) default 0,
  despesa_saldo numeric(15, 2) default 0,
  despesa_documento varchar(400),
  despesa_finalidade varchar(100),
  despesa_evento integer,
  despesa_projeto integer
);

create table public.movimento_estoque (
  movimentoest_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  movimentoest_numero integer,
  movimentoest_operacao integer,
  movimentoest_emissao date,
  movimentoest_sinal char(1),
  movimentoest_produto integer references public.produto (produto_id),
  movimentoest_quantidade numeric(15, 3) default 0,
  movimentoest_unitario numeric(15, 2) default 0,
  movimentoest_total numeric(15, 2) default 0,
  movimentoest_ramo integer,
  movimentoest_secao integer,
  movimentoest_secaonome integer
);

-- Helper: empresa do usuário logado
create or replace function public.current_empresa_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select empresa_id from public.profiles where id = auth.uid();
$$;

-- RLS
alter table public.profiles enable row level security;
alter table public.empresa enable row level security;
alter table public.ramos enable row level security;
alter table public.estado enable row level security;
alter table public.cidade enable row level security;
alter table public.categoria enable row level security;
alter table public.funcao enable row level security;
alter table public.secao enable row level security;
alter table public.secao_nome enable row level security;
alter table public.tipo_mensalidade enable row level security;
alter table public.tipo_pagamento enable row level security;
alter table public.associados enable row level security;
alter table public.grupo_produto enable row level security;
alter table public.produto enable row level security;
alter table public.produto_custo enable row level security;
alter table public.produto_preco enable row level security;
alter table public.fornecedor_despesa enable row level security;
alter table public.despesas enable row level security;
alter table public.movimento_estoque enable row level security;

create policy "profiles_select_own" on public.profiles
  for select using (id = auth.uid());

create policy "profiles_update_own" on public.profiles
  for update using (id = auth.uid());

create policy "empresa_select_own" on public.empresa
  for select using (id = public.current_empresa_id());

create policy "lookups_read_auth" on public.ramos
  for select to authenticated using (true);
create policy "estado_read_auth" on public.estado
  for select to authenticated using (true);
create policy "cidade_read_auth" on public.cidade
  for select to authenticated using (true);
create policy "categoria_read_auth" on public.categoria
  for select to authenticated using (true);
create policy "funcao_read_auth" on public.funcao
  for select to authenticated using (true);

create policy "secao_tenant" on public.secao
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "secao_nome_tenant" on public.secao_nome
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "tipo_mensalidade_tenant" on public.tipo_mensalidade
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "tipo_pagamento_tenant" on public.tipo_pagamento
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "associados_tenant" on public.associados
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "grupo_produto_tenant" on public.grupo_produto
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "produto_tenant" on public.produto
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "produto_custo_tenant" on public.produto_custo
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "produto_preco_tenant" on public.produto_preco
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "fornecedor_tenant" on public.fornecedor_despesa
  for all using (empresa_id = public.current_empresa_id() or empresa_id is null)
  with check (empresa_id = public.current_empresa_id());

create policy "despesas_tenant" on public.despesas
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

create policy "movimento_estoque_tenant" on public.movimento_estoque
  for all using (empresa_id = public.current_empresa_id())
  with check (empresa_id = public.current_empresa_id());

-- Dashboard: contagem por ramo
create or replace function public.dashboard_contagem_ramos()
returns table (ramo_id integer, ramo_nome text, total bigint)
language sql
stable
security invoker
set search_path = public
as $$
  select
    r.ramo_id,
    r.nome::text as ramo_nome,
    count(a.associado_id) as total
  from public.ramos r
  left join public.associados a
    on a.ramo = r.ramo_id
   and a.empresa_id = public.current_empresa_id()
   and coalesce(a.ativo, true) = true
  group by r.ramo_id, r.nome
  order by r.ramo_id;
$$;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_empresa_id() to authenticated;
grant execute on function public.dashboard_contagem_ramos() to authenticated;
