-- Baixas / pagamentos de despesas

create table if not exists public.despesa_pagamento (
  pagamento_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  despesa_id integer not null references public.despesas (despesa_id) on delete cascade,
  tipopagto_id integer references public.tipo_pagamento (tipopagto_id),
  data_pagamento date not null default current_date,
  valor numeric(15, 2) not null check (valor > 0),
  observacao varchar(200),
  created_at timestamptz not null default now()
);

create index if not exists despesa_pagamento_despesa_idx
  on public.despesa_pagamento (despesa_id);

create index if not exists despesa_pagamento_empresa_idx
  on public.despesa_pagamento (empresa_id);

alter table public.despesa_pagamento enable row level security;

drop policy if exists "despesa_pagamento_tenant" on public.despesa_pagamento;
create policy "despesa_pagamento_tenant"
  on public.despesa_pagamento
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.despesa_pagamento to authenticated;
grant usage, select on all sequences in schema public to authenticated;
