-- Receitas (avulsas e mensalidades) + baixas

create table if not exists public.receitas (
  receita_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  associado_id integer references public.associados (associado_id),
  tipomensalidade_id integer references public.tipo_mensalidade (tipomensalidade_id),
  receita_origem char(1) not null default 'A', -- A=avulsa M=mensalidade
  receita_descricao varchar(120),
  receita_ramo integer,
  receita_secao integer,
  receita_emissao date,
  receita_vencimento date,
  receita_competencia date, -- 1º dia do mês de referência (mensalidade)
  receita_valor numeric(15, 2) not null default 0,
  receita_saldo numeric(15, 2) not null default 0,
  receita_situacao integer not null default 1, -- 1 aberto 2 parcial 3 pago
  receita_observacao varchar(200),
  created_at timestamptz not null default now()
);

create index if not exists receitas_empresa_idx on public.receitas (empresa_id);
create index if not exists receitas_situacao_idx on public.receitas (empresa_id, receita_situacao);
create index if not exists receitas_associado_idx on public.receitas (associado_id);

create unique index if not exists receitas_mensalidade_uidx
  on public.receitas (empresa_id, associado_id, receita_competencia)
  where receita_origem = 'M'
    and associado_id is not null
    and receita_competencia is not null;

create table if not exists public.receita_pagamento (
  pagamento_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  receita_id integer not null references public.receitas (receita_id) on delete cascade,
  tipopagto_id integer references public.tipo_pagamento (tipopagto_id),
  data_pagamento date not null default current_date,
  valor numeric(15, 2) not null check (valor > 0),
  observacao varchar(200),
  created_at timestamptz not null default now()
);

create index if not exists receita_pagamento_receita_idx
  on public.receita_pagamento (receita_id);

alter table public.receitas enable row level security;
alter table public.receita_pagamento enable row level security;

drop policy if exists "receitas_tenant" on public.receitas;
create policy "receitas_tenant"
  on public.receitas
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

drop policy if exists "receita_pagamento_tenant" on public.receita_pagamento;
create policy "receita_pagamento_tenant"
  on public.receita_pagamento
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.receitas to authenticated;
grant select, insert, update, delete on public.receita_pagamento to authenticated;
grant usage, select on all sequences in schema public to authenticated;
