-- Atividades do grupo (por ramo / seção / patrulha)

create table if not exists public.atividades (
  atividade_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  patrulha_matilha integer references public.secao_nome (secaonome_id),
  descricao varchar(200) not null,
  local varchar(120),
  valor numeric(15, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists atividades_empresa_idx
  on public.atividades (empresa_id);

create index if not exists atividades_empresa_ramo_idx
  on public.atividades (empresa_id, ramo);

alter table public.atividades enable row level security;

drop policy if exists "atividades_tenant" on public.atividades;
create policy "atividades_tenant"
  on public.atividades
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.atividades to authenticated;
grant usage, select on all sequences in schema public to authenticated;
