-- Confirmacao de participacao e pagamento de atividades (por associado)

create table if not exists public.atividade_confirmacao (
  confirmacao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  atividade_id integer not null references public.atividades (atividade_id) on delete cascade,
  associado_id integer not null references public.associados (associado_id) on delete cascade,
  confirmado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (atividade_id, associado_id)
);

create index if not exists atividade_confirmacao_associado_idx
  on public.atividade_confirmacao (associado_id);

create index if not exists atividade_confirmacao_atividade_idx
  on public.atividade_confirmacao (atividade_id);

create table if not exists public.atividade_pagamento (
  pagamento_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  atividade_id integer not null references public.atividades (atividade_id) on delete cascade,
  associado_id integer not null references public.associados (associado_id) on delete cascade,
  valor numeric(15, 2) not null default 0,
  pago_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (atividade_id, associado_id)
);

create index if not exists atividade_pagamento_associado_idx
  on public.atividade_pagamento (associado_id);

create index if not exists atividade_pagamento_atividade_idx
  on public.atividade_pagamento (atividade_id);

alter table public.atividade_confirmacao enable row level security;
alter table public.atividade_pagamento enable row level security;

drop policy if exists "atividade_confirmacao_tenant" on public.atividade_confirmacao;
create policy "atividade_confirmacao_tenant"
  on public.atividade_confirmacao
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

drop policy if exists "atividade_pagamento_tenant" on public.atividade_pagamento;
create policy "atividade_pagamento_tenant"
  on public.atividade_pagamento
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.atividade_confirmacao to authenticated;
grant select, insert, update, delete on public.atividade_pagamento to authenticated;
grant usage, select on all sequences in schema public to authenticated;
