-- Projetos do grupo (por ramo / seção ou grupo todo)

create table if not exists public.projetos (
  projeto_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  descricao varchar(200) not null,
  valor numeric(15, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists projetos_empresa_idx
  on public.projetos (empresa_id);

create index if not exists projetos_empresa_ramo_idx
  on public.projetos (empresa_id, ramo);

alter table public.projetos enable row level security;

drop policy if exists "projetos_tenant" on public.projetos;
create policy "projetos_tenant"
  on public.projetos
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.projetos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Vínculo em despesas e receitas
alter table public.despesas
  add column if not exists projeto_id integer
    references public.projetos (projeto_id) on delete set null;

alter table public.receitas
  add column if not exists projeto_id integer
    references public.projetos (projeto_id) on delete set null;

create index if not exists despesas_projeto_idx
  on public.despesas (projeto_id);

create index if not exists receitas_projeto_idx
  on public.receitas (projeto_id);
