-- Ação entre amigos (rifa): números inicial/final por ramo/seção/patrulha

create table if not exists public.acao_entre_amigos (
  acao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  patrulha_matilha integer references public.secao_nome (secaonome_id),
  nome varchar(200) not null,
  numero_inicial integer not null,
  numero_final integer not null,
  created_at timestamptz not null default now(),
  constraint acao_entre_amigos_numeros_chk
    check (numero_inicial >= 0 and numero_final >= numero_inicial)
);

create index if not exists acao_entre_amigos_empresa_idx
  on public.acao_entre_amigos (empresa_id);

create index if not exists acao_entre_amigos_empresa_ramo_idx
  on public.acao_entre_amigos (empresa_id, ramo);

alter table public.acao_entre_amigos enable row level security;

drop policy if exists "acao_entre_amigos_tenant" on public.acao_entre_amigos;
create policy "acao_entre_amigos_tenant"
  on public.acao_entre_amigos
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.acao_entre_amigos to authenticated;
grant usage, select on all sequences in schema public to authenticated;
