-- Valor por número, faixas por jovem e vendas da ação entre amigos

alter table public.acao_entre_amigos
  add column if not exists valor_numero numeric(15, 2) not null default 0;

create table if not exists public.acao_entre_amigos_faixa (
  faixa_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  acao_id integer not null
    references public.acao_entre_amigos (acao_id) on delete cascade,
  associado_id integer not null
    references public.associados (associado_id) on delete cascade,
  numero_inicial integer not null,
  numero_final integer not null,
  created_at timestamptz not null default now(),
  constraint acao_entre_amigos_faixa_numeros_chk
    check (numero_inicial >= 0 and numero_final >= numero_inicial),
  constraint acao_entre_amigos_faixa_associado_uq
    unique (acao_id, associado_id)
);

create index if not exists acao_entre_amigos_faixa_acao_idx
  on public.acao_entre_amigos_faixa (acao_id);

create index if not exists acao_entre_amigos_faixa_associado_idx
  on public.acao_entre_amigos_faixa (associado_id);

alter table public.acao_entre_amigos_faixa enable row level security;

drop policy if exists "acao_entre_amigos_faixa_tenant"
  on public.acao_entre_amigos_faixa;
create policy "acao_entre_amigos_faixa_tenant"
  on public.acao_entre_amigos_faixa
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete
  on public.acao_entre_amigos_faixa to authenticated;

create table if not exists public.acao_entre_amigos_venda (
  venda_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  acao_id integer not null
    references public.acao_entre_amigos (acao_id) on delete cascade,
  numero integer not null,
  comprador_nome varchar(200) not null,
  comprador_telefone varchar(40) not null,
  valor numeric(15, 2) not null default 0,
  associado_vendedor_id integer
    references public.associados (associado_id) on delete set null,
  vendido_por uuid references auth.users (id) on delete set null,
  vendido_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint acao_entre_amigos_venda_numero_uq unique (acao_id, numero)
);

create index if not exists acao_entre_amigos_venda_acao_idx
  on public.acao_entre_amigos_venda (acao_id);

create index if not exists acao_entre_amigos_venda_vendedor_idx
  on public.acao_entre_amigos_venda (associado_vendedor_id);

alter table public.acao_entre_amigos_venda enable row level security;

drop policy if exists "acao_entre_amigos_venda_tenant"
  on public.acao_entre_amigos_venda;
create policy "acao_entre_amigos_venda_tenant"
  on public.acao_entre_amigos_venda
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete
  on public.acao_entre_amigos_venda to authenticated;

grant usage, select on all sequences in schema public to authenticated;
