-- Eventos (venda de convites por quantidade, numeração automática)

create table if not exists public.venda_eventos (
  evento_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  nome varchar(200) not null,
  numero_inicial integer not null,
  numero_final integer not null,
  valor_convite numeric(15, 2) not null default 0,
  data_evento date,
  imagem_url text,
  created_at timestamptz not null default now(),
  constraint venda_eventos_numeros_chk
    check (numero_inicial >= 0 and numero_final >= numero_inicial)
);

create index if not exists venda_eventos_empresa_idx
  on public.venda_eventos (empresa_id);

alter table public.venda_eventos enable row level security;

drop policy if exists "venda_eventos_tenant" on public.venda_eventos;
create policy "venda_eventos_tenant"
  on public.venda_eventos
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.venda_eventos to authenticated;

create table if not exists public.venda_evento_compra (
  compra_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  evento_id integer not null
    references public.venda_eventos (evento_id) on delete cascade,
  quantidade integer not null check (quantidade > 0),
  comprador_telefone varchar(40),
  valor numeric(15, 2) not null default 0,
  forma_pagamento text
    check (
      forma_pagamento is null
      or forma_pagamento in ('dinheiro', 'pix_direto')
    ),
  vendido_por uuid references auth.users (id) on delete set null,
  vendido_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists venda_evento_compra_evento_idx
  on public.venda_evento_compra (evento_id);

alter table public.venda_evento_compra enable row level security;

drop policy if exists "venda_evento_compra_tenant" on public.venda_evento_compra;
create policy "venda_evento_compra_tenant"
  on public.venda_evento_compra
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete
  on public.venda_evento_compra to authenticated;

create table if not exists public.venda_evento_convite (
  convite_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  evento_id integer not null
    references public.venda_eventos (evento_id) on delete cascade,
  compra_id integer not null
    references public.venda_evento_compra (compra_id) on delete cascade,
  numero integer not null,
  nome varchar(200) not null,
  created_at timestamptz not null default now(),
  constraint venda_evento_convite_numero_uq unique (evento_id, numero)
);

create index if not exists venda_evento_convite_evento_idx
  on public.venda_evento_convite (evento_id);

create index if not exists venda_evento_convite_compra_idx
  on public.venda_evento_convite (compra_id);

alter table public.venda_evento_convite enable row level security;

drop policy if exists "venda_evento_convite_tenant"
  on public.venda_evento_convite;
create policy "venda_evento_convite_tenant"
  on public.venda_evento_convite
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete
  on public.venda_evento_convite to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- Compra atômica: quantidade + nomes → próximos números livres
create or replace function public.venda_evento_comprar(
  p_evento_id integer,
  p_nomes text[],
  p_comprador_telefone text default null,
  p_forma_pagamento text default null
)
returns table (
  ok boolean,
  mensagem text,
  compra_id integer,
  numeros integer[]
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_evento public.venda_eventos%rowtype;
  v_qtde integer;
  v_nomes text[];
  v_n integer;
  v_free integer[] := '{}';
  v_compra_id integer;
  v_valor numeric(15, 2);
  v_fone text;
  v_forma text;
begin
  if auth.uid() is null then
    return query select false, 'Não autenticado.'::text, null::integer, '{}'::integer[];
    return;
  end if;

  select * into v_evento
  from public.venda_eventos e
  where e.evento_id = p_evento_id
    and public.can_access_empresa(e.empresa_id)
  for update;

  if not found then
    return query select false, 'Evento não encontrado.'::text, null::integer, '{}'::integer[];
    return;
  end if;

  v_nomes := array(
    select left(btrim(x), 200)
    from unnest(coalesce(p_nomes, '{}'::text[])) as x
    where btrim(coalesce(x, '')) <> ''
  );
  v_qtde := coalesce(cardinality(v_nomes), 0);

  if v_qtde <= 0 then
    return query select false, 'Informe ao menos um nome.'::text, null::integer, '{}'::integer[];
    return;
  end if;

  v_fone := nullif(left(btrim(coalesce(p_comprador_telefone, '')), 40), '');
  v_forma := nullif(btrim(coalesce(p_forma_pagamento, '')), '');
  if v_forma is not null and v_forma not in ('dinheiro', 'pix_direto') then
    return query select false, 'Forma de pagamento inválida.'::text, null::integer, '{}'::integer[];
    return;
  end if;

  for v_n in v_evento.numero_inicial .. v_evento.numero_final loop
    if not exists (
      select 1
      from public.venda_evento_convite c
      where c.evento_id = v_evento.evento_id
        and c.numero = v_n
    ) then
      v_free := array_append(v_free, v_n);
      exit when cardinality(v_free) >= v_qtde;
    end if;
  end loop;

  if cardinality(v_free) < v_qtde then
    return query
      select
        false,
        (
          'Só há ' || coalesce(cardinality(v_free), 0)::text ||
          ' convite(s) disponível(is).'
        )::text,
        null::integer,
        '{}'::integer[];
    return;
  end if;

  v_valor := round(coalesce(v_evento.valor_convite, 0) * v_qtde, 2);

  insert into public.venda_evento_compra (
    empresa_id,
    evento_id,
    quantidade,
    comprador_telefone,
    valor,
    forma_pagamento,
    vendido_por
  ) values (
    v_evento.empresa_id,
    v_evento.evento_id,
    v_qtde,
    v_fone,
    v_valor,
    v_forma,
    auth.uid()
  )
  returning venda_evento_compra.compra_id into v_compra_id;

  for v_n in 1 .. v_qtde loop
    insert into public.venda_evento_convite (
      empresa_id,
      evento_id,
      compra_id,
      numero,
      nome
    ) values (
      v_evento.empresa_id,
      v_evento.evento_id,
      v_compra_id,
      v_free[v_n],
      v_nomes[v_n]
    );
  end loop;

  return query
    select
      true,
      (
        case
          when v_qtde = 1 then 'Convite ' || v_free[1]::text || ' registrado.'
          else
            v_qtde::text || ' convites registrados: ' ||
            array_to_string(v_free, ', ')
        end
      )::text,
      v_compra_id,
      v_free;
end;
$$;

revoke all on function public.venda_evento_comprar(integer, text[], text, text)
  from public;
grant execute on function public.venda_evento_comprar(integer, text[], text, text)
  to authenticated;

-- Storage da imagem do evento
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'venda-eventos',
  'venda-eventos',
  true,
  2097152,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "venda_eventos_img_public_read" on storage.objects;
create policy "venda_eventos_img_public_read"
  on storage.objects
  for select
  using (bucket_id = 'venda-eventos');

drop policy if exists "venda_eventos_img_tenant_insert" on storage.objects;
create policy "venda_eventos_img_tenant_insert"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'venda-eventos'
    and (
      public.is_super_admin()
      or (storage.foldername(name))[1] = public.current_empresa_id()::text
    )
  );

drop policy if exists "venda_eventos_img_tenant_update" on storage.objects;
create policy "venda_eventos_img_tenant_update"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'venda-eventos'
    and (
      public.is_super_admin()
      or (storage.foldername(name))[1] = public.current_empresa_id()::text
    )
  )
  with check (
    bucket_id = 'venda-eventos'
    and (
      public.is_super_admin()
      or (storage.foldername(name))[1] = public.current_empresa_id()::text
    )
  );

drop policy if exists "venda_eventos_img_tenant_delete" on storage.objects;
create policy "venda_eventos_img_tenant_delete"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'venda-eventos'
    and (
      public.is_super_admin()
      or (storage.foldername(name))[1] = public.current_empresa_id()::text
    )
  );
