-- Cadastro de conquistas máximas por associado (por grupo).

create table if not exists public.conquistas (
  conquista_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  associado_id integer not null references public.associados (associado_id) on delete cascade,
  ramo integer references public.ramos (ramo_id) on delete set null,
  secao integer references public.secao (secao_id) on delete set null,
  patrulha_matilha integer references public.secao_nome (secaonome_id) on delete set null,
  tipo text not null
    check (
      tipo in (
        'cruzeiro_do_sul',
        'lis_de_ouro',
        'escoteiro_patria',
        'insignia_bp',
        'insignia_madeira'
      )
    ),
  data_conquista date,
  observacao varchar(300),
  created_at timestamptz not null default now(),
  unique (empresa_id, associado_id, tipo)
);

comment on table public.conquistas is
  'Conquistas máximas dos associados: Cruzeiro do Sul, Lis de Ouro, Escoteiro da Pátria, Insígnia de B.P. e Insígnia da Madeira.';

create index if not exists conquistas_empresa_idx
  on public.conquistas (empresa_id);

create index if not exists conquistas_empresa_tipo_idx
  on public.conquistas (empresa_id, tipo);

create index if not exists conquistas_associado_idx
  on public.conquistas (associado_id);

alter table public.conquistas enable row level security;

drop policy if exists "conquistas_tenant" on public.conquistas;
create policy "conquistas_tenant"
  on public.conquistas
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.conquistas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Migra marcações já existentes no cadastro do associado.
insert into public.conquistas (
  empresa_id,
  associado_id,
  ramo,
  secao,
  patrulha_matilha,
  tipo,
  data_conquista
)
select
  a.empresa_id,
  a.associado_id,
  a.ramo,
  a.secao,
  a.patrulha_matilha,
  v.tipo,
  v.data_conquista
from public.associados a
cross join lateral (
  values
    (
      'cruzeiro_do_sul'::text,
      a.conquista_cruzeiro_do_sul,
      a.conquista_cruzeiro_do_sul_data
    ),
    (
      'lis_de_ouro',
      a.conquista_lis_de_ouro,
      a.conquista_lis_de_ouro_data
    ),
    (
      'escoteiro_patria',
      a.conquista_escoteiro_patria,
      a.conquista_escoteiro_patria_data
    ),
    (
      'insignia_bp',
      a.conquista_insignia_bp,
      a.conquista_insignia_bp_data
    ),
    (
      'insignia_madeira',
      a.conquista_insignia_madeira,
      a.conquista_insignia_madeira_data
    )
) as v(tipo, marcado, data_conquista)
where coalesce(v.marcado, false) = true
on conflict (empresa_id, associado_id, tipo) do nothing;
