-- Competições entre matilhas/patrulhas de uma seção

create table if not exists public.competicoes (
  competicao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  secao_id integer not null references public.secao (secao_id),
  nome varchar(120) not null,
  descricao varchar(500),
  data_inicio date,
  data_fim date,
  encerrado_em timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.competicao_participante (
  participante_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  competicao_id integer not null
    references public.competicoes (competicao_id) on delete cascade,
  secaonome_id integer not null
    references public.secao_nome (secaonome_id),
  created_at timestamptz not null default now(),
  unique (competicao_id, secaonome_id)
);

create table if not exists public.competicao_prova (
  prova_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  competicao_id integer not null
    references public.competicoes (competicao_id) on delete cascade,
  nome varchar(120) not null,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.competicao_pontuacao (
  pontuacao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  prova_id integer not null
    references public.competicao_prova (prova_id) on delete cascade,
  participante_id integer not null
    references public.competicao_participante (participante_id) on delete cascade,
  pontos numeric(10, 2) not null default 0,
  observacao varchar(200),
  updated_at timestamptz not null default now(),
  unique (prova_id, participante_id)
);

create index if not exists competicoes_empresa_idx
  on public.competicoes (empresa_id, created_at desc);
create index if not exists competicoes_secao_idx
  on public.competicoes (empresa_id, secao_id);
create index if not exists competicao_participante_competicao_idx
  on public.competicao_participante (competicao_id);
create index if not exists competicao_prova_competicao_idx
  on public.competicao_prova (competicao_id, ordem, prova_id);
create index if not exists competicao_pontuacao_prova_idx
  on public.competicao_pontuacao (prova_id);

alter table public.competicoes enable row level security;
alter table public.competicao_participante enable row level security;
alter table public.competicao_prova enable row level security;
alter table public.competicao_pontuacao enable row level security;

create or replace function public.can_write_competicoes(p_empresa_id integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_access_empresa(p_empresa_id)
     and coalesce(public.current_user_role(), 'leitura'::public.app_role)
         in (
           'super_admin'::public.app_role,
           'admin'::public.app_role,
           'chefe'::public.app_role,
           'escotista'::public.app_role
         );
$$;

grant execute on function public.can_write_competicoes(integer)
  to authenticated;

do $$
begin
  perform public.harden_tenant_write_policies(
    'competicoes',
    'can_write_competicoes'
  );
  perform public.harden_tenant_write_policies(
    'competicao_participante',
    'can_write_competicoes'
  );
  perform public.harden_tenant_write_policies(
    'competicao_prova',
    'can_write_competicoes'
  );
  perform public.harden_tenant_write_policies(
    'competicao_pontuacao',
    'can_write_competicoes'
  );

  perform public.auditoria_attach('competicoes', 'competicao_id');
  perform public.auditoria_attach(
    'competicao_participante',
    'participante_id'
  );
  perform public.auditoria_attach('competicao_prova', 'prova_id');
  perform public.auditoria_attach('competicao_pontuacao', 'pontuacao_id');
end;
$$;

grant select, insert, update, delete on
  public.competicoes,
  public.competicao_participante,
  public.competicao_prova,
  public.competicao_pontuacao
to authenticated;

grant usage, select on all sequences in schema public to authenticated;
