-- Solicitações de voluntários (não beneficiários) por ramo/seção.

create table if not exists public.solicitacoes (
  solicitacao_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  ramo_id integer not null references public.ramos (ramo_id),
  secao_id integer not null references public.secao (secao_id),
  texto text not null,
  data_solicitacao date not null default (current_date),
  resolvida boolean not null default false,
  data_resolvida date null,
  user_id uuid null references auth.users (id) on delete set null,
  user_nome text null,
  created_at timestamptz not null default now(),
  constraint solicitacoes_resolvida_data_chk check (
    resolvida = false
    or data_resolvida is not null
  )
);

comment on table public.solicitacoes is
  'Solicitações internas do grupo (ramo/seção), abertas por voluntários.';

create index if not exists solicitacoes_empresa_idx
  on public.solicitacoes (empresa_id, data_solicitacao desc, solicitacao_id desc);

create index if not exists solicitacoes_empresa_resolvida_idx
  on public.solicitacoes (empresa_id, resolvida, data_solicitacao desc);

create index if not exists solicitacoes_ramo_secao_idx
  on public.solicitacoes (empresa_id, ramo_id, secao_id);

alter table public.solicitacoes enable row level security;

create or replace function public.can_write_solicitacoes(p_empresa_id integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_access_empresa(p_empresa_id)
     and coalesce(public.current_user_role(), 'leitura'::public.app_role)
         in (
           'super_admin'::public.app_role,
           'admin'::public.app_role,
           'tesoureiro'::public.app_role,
           'chefe'::public.app_role,
           'escotista'::public.app_role,
           'leitura'::public.app_role
         );
$$;

comment on function public.can_write_solicitacoes(integer) is
  'Voluntários (incl. portal leitura) podem criar/editar solicitações do próprio grupo.';

grant execute on function public.can_write_solicitacoes(integer)
  to authenticated;

do $$
begin
  perform public.harden_tenant_write_policies(
    'solicitacoes',
    'can_write_solicitacoes'
  );
  perform public.auditoria_attach('solicitacoes', 'solicitacao_id');
end;
$$;

grant select, insert, update, delete on public.solicitacoes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
