-- Plano de contas do grupo, para classificar fornecedores/contatos
-- e, depois, agrupar os lançamentos no Portal da Transparência.

create table public.plano_contas (
  plano_conta_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  codigo text not null,
  nome text not null,
  natureza text not null default 'despesa',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint plano_contas_codigo_uk unique (empresa_id, codigo),
  constraint plano_contas_natureza_chk check (natureza in ('receita', 'despesa'))
);

create index plano_contas_empresa_idx on public.plano_contas (empresa_id, codigo);

alter table public.fornecedor_despesa
  add column plano_conta_id integer references public.plano_contas (plano_conta_id) on delete set null;

create index fornecedor_despesa_plano_conta_idx
  on public.fornecedor_despesa (plano_conta_id);

alter table public.plano_contas enable row level security;

select public.harden_tenant_write_policies('plano_contas', 'can_write_financeiro');

select public.auditoria_attach('plano_contas', 'plano_conta_id');

grant select, insert, update, delete on public.plano_contas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
