-- Orçamento do que a atividade ou o evento precisa para acontecer.

create table public.orcamentos (
  orcamento_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  atividade_id integer references public.atividades (atividade_id) on delete cascade,
  evento_id integer references public.venda_eventos (evento_id) on delete cascade,
  observacao text,
  created_at timestamptz not null default now(),
  constraint orcamentos_destino_chk check (
    (atividade_id is not null and evento_id is null)
    or (atividade_id is null and evento_id is not null)
  )
);

create unique index orcamentos_atividade_uk
  on public.orcamentos (empresa_id, atividade_id)
  where atividade_id is not null;

create unique index orcamentos_evento_uk
  on public.orcamentos (empresa_id, evento_id)
  where evento_id is not null;

create index orcamentos_empresa_idx on public.orcamentos (empresa_id);

create table public.orcamento_itens (
  orcamento_item_id integer generated by default as identity primary key,
  orcamento_id integer not null references public.orcamentos (orcamento_id) on delete cascade,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  descricao text not null,
  quantidade numeric(12, 3) not null default 1,
  unidade text not null default 'un',
  valor_unitario numeric(12, 2) not null default 0,
  ordem integer not null default 0,
  constraint orcamento_itens_quantidade_chk check (quantidade > 0),
  constraint orcamento_itens_valor_chk check (valor_unitario >= 0)
);

create index orcamento_itens_orcamento_idx
  on public.orcamento_itens (orcamento_id, ordem);

alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;

select public.harden_tenant_write_policies('orcamentos', 'can_write_financeiro');
select public.harden_tenant_write_policies('orcamento_itens', 'can_write_financeiro');

select public.auditoria_attach('orcamentos', 'orcamento_id');
select public.auditoria_attach('orcamento_itens', 'orcamento_item_id');

grant select, insert, update, delete on public.orcamentos to authenticated;
grant select, insert, update, delete on public.orcamento_itens to authenticated;
grant usage, select on all sequences in schema public to authenticated;
