-- Chamada de assiduidade do ramo: data, atividade e presença
-- de jovens e voluntários.

create table public.assiduidade (
  assiduidade_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  ramo integer not null references public.ramos (ramo_id),
  data_atividade date not null,
  atividade_id integer not null references public.atividades (atividade_id),
  created_at timestamptz not null default now(),
  constraint assiduidade_ramo_atividade_uk unique (empresa_id, ramo, atividade_id)
);

create index assiduidade_empresa_idx
  on public.assiduidade (empresa_id, data_atividade desc);

create table public.assiduidade_presenca (
  assiduidade_presenca_id integer generated by default as identity primary key,
  assiduidade_id integer not null references public.assiduidade (assiduidade_id) on delete cascade,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  associado_id integer not null references public.associados (associado_id) on delete cascade,
  compareceu boolean not null default false,
  constraint assiduidade_presenca_pessoa_uk unique (assiduidade_id, associado_id)
);

create index assiduidade_presenca_assiduidade_idx
  on public.assiduidade_presenca (assiduidade_id);

alter table public.assiduidade enable row level security;
alter table public.assiduidade_presenca enable row level security;

select public.harden_tenant_write_policies('assiduidade', 'can_write_empresa');
select public.harden_tenant_write_policies('assiduidade_presenca', 'can_write_empresa');

select public.auditoria_attach('assiduidade', 'assiduidade_id');
select public.auditoria_attach('assiduidade_presenca', 'assiduidade_presenca_id');

grant select, insert, update, delete on public.assiduidade to authenticated;
grant select, insert, update, delete on public.assiduidade_presenca to authenticated;
grant usage, select on all sequences in schema public to authenticated;
