-- Pedidos InfinitePay (Checkout Integrado) para venda de convites de eventos

create table if not exists public.infinitepay_pedidos (
  id bigint generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  evento_id integer not null references public.venda_eventos (evento_id) on delete cascade,
  order_nsu text not null,
  handle text not null,
  nomes text[] not null default '{}',
  comprador_telefone text,
  comprador_nome text,
  valor numeric(15, 2) not null,
  descricao text,
  status text not null default 'pendente'
    check (status in ('pendente', 'pago', 'cancelado', 'erro')),
  checkout_url text,
  invoice_slug text,
  transaction_nsu text,
  capture_method text,
  receipt_url text,
  compra_id integer references public.venda_evento_compra (compra_id) on delete set null,
  raw_create jsonb,
  raw_webhook jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint infinitepay_pedidos_order_nsu_uq unique (order_nsu)
);

create index if not exists infinitepay_pedidos_evento_idx
  on public.infinitepay_pedidos (evento_id);

create index if not exists infinitepay_pedidos_empresa_idx
  on public.infinitepay_pedidos (empresa_id);

create index if not exists infinitepay_pedidos_status_idx
  on public.infinitepay_pedidos (status);

alter table public.infinitepay_pedidos enable row level security;

drop policy if exists "infinitepay_pedidos_tenant" on public.infinitepay_pedidos;
create policy "infinitepay_pedidos_tenant"
  on public.infinitepay_pedidos
  for select
  to authenticated
  using (public.can_access_empresa(empresa_id));

grant select on public.infinitepay_pedidos to authenticated;
grant all on public.infinitepay_pedidos to service_role;
grant usage, select on all sequences in schema public to service_role;

alter table public.venda_evento_compra
  drop constraint if exists venda_evento_compra_forma_pagamento_check;

alter table public.venda_evento_compra
  add constraint venda_evento_compra_forma_pagamento_check
  check (
    forma_pagamento is null
    or forma_pagamento in ('dinheiro', 'pix_direto', 'pix', 'infinitepay')
  );

alter table public.venda_evento_compra
  add column if not exists infinitepay_pedido_id bigint
    references public.infinitepay_pedidos (id) on delete set null;

create index if not exists venda_evento_compra_infinitepay_idx
  on public.venda_evento_compra (infinitepay_pedido_id);
