-- Calendário do grupo (eventos por ramo / seção)

create table if not exists public.calendario_grupo (
  id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  ramo integer references public.ramos (ramo_id),
  secao integer references public.secao (secao_id),
  titulo varchar(160) not null,
  descricao text,
  local varchar(160),
  data_inicio date not null,
  data_fim date,
  hora_inicio time,
  hora_fim time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists calendario_grupo_empresa_idx
  on public.calendario_grupo (empresa_id);

create index if not exists calendario_grupo_empresa_data_idx
  on public.calendario_grupo (empresa_id, data_inicio);

create index if not exists calendario_grupo_empresa_ramo_idx
  on public.calendario_grupo (empresa_id, ramo);

comment on table public.calendario_grupo is
  'Agenda do grupo. ramo/seção nulos = evento do grupo inteiro.';

alter table public.calendario_grupo enable row level security;

drop policy if exists "calendario_grupo_tenant" on public.calendario_grupo;
create policy "calendario_grupo_tenant"
  on public.calendario_grupo
  for all
  to authenticated
  using (public.can_access_empresa(empresa_id))
  with check (public.can_access_empresa(empresa_id));

grant select, insert, update, delete on public.calendario_grupo to authenticated;
grant usage, select on all sequences in schema public to authenticated;
