-- Pedidos da loja online: listagem + marcação de entrega

create table if not exists public.loja_pedido (
  pedido_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id),
  receita_id integer references public.receitas (receita_id) on delete set null,
  canal text not null default 'online'
    check (canal in ('online', 'local')),
  comprador_nome text,
  comprador_telefone text,
  associado_id integer references public.associados (associado_id) on delete set null,
  total numeric(15, 2) not null default 0,
  observacao text,
  criado_por uuid references auth.users (id) on delete set null,
  entregue_em timestamptz,
  entregue_por uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists loja_pedido_empresa_idx
  on public.loja_pedido (empresa_id, created_at desc);

create index if not exists loja_pedido_receita_idx
  on public.loja_pedido (receita_id);

create index if not exists loja_pedido_pendente_idx
  on public.loja_pedido (empresa_id, created_at desc)
  where entregue_em is null and canal = 'online';

create table if not exists public.loja_pedido_item (
  item_id integer generated by default as identity primary key,
  pedido_id integer not null
    references public.loja_pedido (pedido_id) on delete cascade,
  empresa_id integer not null references public.empresa (id),
  produto_id integer references public.produto (produto_id) on delete set null,
  nome text not null,
  quantidade numeric(15, 3) not null default 1,
  unitario numeric(15, 2) not null default 0,
  total numeric(15, 2) not null default 0
);

create index if not exists loja_pedido_item_pedido_idx
  on public.loja_pedido_item (pedido_id);

alter table public.loja_pedido enable row level security;
alter table public.loja_pedido_item enable row level security;

drop policy if exists "loja_pedido_select" on public.loja_pedido;
create policy "loja_pedido_select"
  on public.loja_pedido for select to authenticated
  using (public.can_access_empresa(empresa_id));

drop policy if exists "loja_pedido_insert" on public.loja_pedido;
create policy "loja_pedido_insert"
  on public.loja_pedido for insert to authenticated
  with check (public.can_write_empresa(empresa_id));

drop policy if exists "loja_pedido_update" on public.loja_pedido;
create policy "loja_pedido_update"
  on public.loja_pedido for update to authenticated
  using (public.can_write_empresa(empresa_id))
  with check (public.can_write_empresa(empresa_id));

drop policy if exists "loja_pedido_delete" on public.loja_pedido;
create policy "loja_pedido_delete"
  on public.loja_pedido for delete to authenticated
  using (public.can_write_empresa(empresa_id));

drop policy if exists "loja_pedido_item_select" on public.loja_pedido_item;
create policy "loja_pedido_item_select"
  on public.loja_pedido_item for select to authenticated
  using (public.can_access_empresa(empresa_id));

drop policy if exists "loja_pedido_item_insert" on public.loja_pedido_item;
create policy "loja_pedido_item_insert"
  on public.loja_pedido_item for insert to authenticated
  with check (public.can_write_empresa(empresa_id));

drop policy if exists "loja_pedido_item_update" on public.loja_pedido_item;
create policy "loja_pedido_item_update"
  on public.loja_pedido_item for update to authenticated
  using (public.can_write_empresa(empresa_id))
  with check (public.can_write_empresa(empresa_id));

drop policy if exists "loja_pedido_item_delete" on public.loja_pedido_item;
create policy "loja_pedido_item_delete"
  on public.loja_pedido_item for delete to authenticated
  using (public.can_write_empresa(empresa_id));

grant select, insert, update, delete on public.loja_pedido to authenticated;
grant select, insert, update, delete on public.loja_pedido_item to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Marcar entregue (staff). Associado não marca.
create or replace function public.loja_pedido_marcar_entregue(
  p_pedido_id integer,
  p_entregue boolean default true
)
returns table (
  ok boolean,
  mensagem text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.loja_pedido%rowtype;
begin
  if auth.uid() is null then
    return query select false, 'Não autenticado.'::text;
    return;
  end if;

  select * into v_row
  from public.loja_pedido p
  where p.pedido_id = p_pedido_id
  for update;

  if not found then
    return query select false, 'Pedido não encontrado.'::text;
    return;
  end if;

  if not public.can_write_empresa(v_row.empresa_id) then
    return query select false, 'Sem permissão para alterar entrega.'::text;
    return;
  end if;

  if p_entregue then
    update public.loja_pedido
    set
      entregue_em = coalesce(entregue_em, now()),
      entregue_por = coalesce(entregue_por, auth.uid())
    where pedido_id = v_row.pedido_id;
    return query select true, 'Pedido marcado como entregue.'::text;
  else
    update public.loja_pedido
    set entregue_em = null, entregue_por = null
    where pedido_id = v_row.pedido_id;
    return query select true, 'Entrega desmarcada.'::text;
  end if;
end;
$$;

revoke all on function public.loja_pedido_marcar_entregue(integer, boolean) from public;
grant execute on function public.loja_pedido_marcar_entregue(integer, boolean)
  to authenticated;

comment on table public.loja_pedido is
  'Pedidos da loja (online/local) para acompanhamento de entrega.';
