-- Mensalidade da plataforma: cobrada por grupo escoteiro (só super_admin).

create table if not exists public.plataforma_plano (
  plano_id integer generated by default as identity primary key,
  nome text not null,
  valor numeric(15, 2) not null default 0 check (valor >= 0),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.plataforma_plano is
  'Planos de mensalidade da plataforma (SaaS), cobrados por grupo.';

alter table public.empresa
  add column if not exists plataforma_plano_id integer
    references public.plataforma_plano (plano_id) on delete set null,
  add column if not exists plataforma_isento boolean not null default false;

create index if not exists empresa_plataforma_plano_idx
  on public.empresa (plataforma_plano_id)
  where plataforma_plano_id is not null;

create table if not exists public.plataforma_cobranca (
  cobranca_id integer generated by default as identity primary key,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  plano_id integer references public.plataforma_plano (plano_id) on delete set null,
  competencia date not null,
  vencimento date,
  descricao text not null,
  valor numeric(15, 2) not null check (valor >= 0),
  saldo numeric(15, 2) not null check (saldo >= 0),
  situacao integer not null default 1
    check (situacao in (1, 2, 3)),
  observacao text,
  pago_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plataforma_cobranca_empresa_comp_uq unique (empresa_id, competencia)
);

create index if not exists plataforma_cobranca_comp_idx
  on public.plataforma_cobranca (competencia desc, situacao);

create index if not exists plataforma_cobranca_empresa_idx
  on public.plataforma_cobranca (empresa_id, competencia desc);

comment on table public.plataforma_cobranca is
  'Mensalidade da plataforma por grupo × competência (1=aberto, 2=parcial, 3=pago).';

create table if not exists public.plataforma_cobranca_pagamento (
  pagamento_id integer generated by default as identity primary key,
  cobranca_id integer not null
    references public.plataforma_cobranca (cobranca_id) on delete cascade,
  empresa_id integer not null references public.empresa (id) on delete cascade,
  data_pagamento date not null default (current_date),
  valor numeric(15, 2) not null check (valor > 0),
  observacao text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists plataforma_cobranca_pag_cobranca_idx
  on public.plataforma_cobranca_pagamento (cobranca_id, data_pagamento desc);

-- RLS: somente super_admin
alter table public.plataforma_plano enable row level security;
alter table public.plataforma_cobranca enable row level security;
alter table public.plataforma_cobranca_pagamento enable row level security;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'super_admin'
      and coalesce(p.ativo, true) = true
  );
$$;

revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to authenticated;

drop policy if exists "plataforma_plano_super" on public.plataforma_plano;
create policy "plataforma_plano_super"
  on public.plataforma_plano
  for all
  to authenticated
  using (public.is_super_admin())
  with check (public.is_super_admin());

drop policy if exists "plataforma_cobranca_super" on public.plataforma_cobranca;
create policy "plataforma_cobranca_super"
  on public.plataforma_cobranca
  for all
  to authenticated
  using (public.is_super_admin())
  with check (public.is_super_admin());

drop policy if exists "plataforma_cobranca_pag_super"
  on public.plataforma_cobranca_pagamento;
create policy "plataforma_cobranca_pag_super"
  on public.plataforma_cobranca_pagamento
  for all
  to authenticated
  using (public.is_super_admin())
  with check (public.is_super_admin());

grant select, insert, update, delete on public.plataforma_plano to authenticated;
grant select, insert, update, delete on public.plataforma_cobranca to authenticated;
grant select, insert, update, delete on public.plataforma_cobranca_pagamento to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Auditoria
do $$
begin
  perform public.auditoria_attach('plataforma_plano', 'plano_id');
  perform public.auditoria_attach('plataforma_cobranca', 'cobranca_id');
  perform public.auditoria_attach('plataforma_cobranca_pagamento', 'pagamento_id');
end;
$$;
